export const countries = [
	{ country: "Argentina", short: "ar" },
	{ country: "Australia", short: "au" },
	{ country: "Austria", short: "at" },
	{ country: "Belgium", short: "be" },
	{ country: "Brazil", short: "br" },
	{ country: "Bulgaria", short: "bg" },
	{ country: "Canada", short: "ca" },
	{ country: "China", short: "cn" },
	{ country: "Colombia", short: "co" },
	{ country: "Cuba", short: "cu" },
	{ country: "Czech Republic", short: "cz" },
	{ country: "Egypt", short: "eg" },
	{ country: "France", short: "fr" },
	{ country: "Germany", short: "de" },
	{ country: "Greece", short: "gr" },
	{ country: "Hong Kong", short: "hk" },
	{ country: "Hungary", short: "hu" },
	{ country: "India", short: "in" },
	{ country: "Indonesia", short: "id" },
	{ country: "Ireland", short: "ie" },
	{ country: "Israel", short: "il" },
	{ country: "Italy", short: "it" },
	{ country: "Japan", short: "jp" },
	{ country: "Latvia", short: "lv" },
	{ country: "Lithuania", short: "lt" },
	{ country: "Malaysia", short: "my" },
	{ country: "Mexico", short: "mx" },
	{ country: "Morocco", short: "ma" },
	{ country: "Netherlands", short: "nl" },
	{ country: "New Zealand", short: "nz" },
	{ country: "Nigeria", short: "ng" },
	{ country: "Norway", short: "no" },
	{ country: "Philippines", short: "ph" },
	{ country: "Poland", short: "pl" },
	{ country: "Portugal", short: "pt" },
	{ country: "Romania", short: "ro" },
	{ country: "Russia", short: "ru" },
	{ country: "Saudi Arabia", short: "sa" },
	{ country: "Serbia", short: "rs" },
	{ country: "Singapore", short: "sg" },
	{ country: "Slovakia", short: "sk" },
	{ country: "Slovenia", short: "si" },
];