export const countries = [
  {country: "Australia", short: "au", url: "australia"},
  {country: "Brazil", short: "br", url: "brazil"},
  {country: "Canada", short: "ca", url: "canada"},
  {country: "China", short: "cn", url: "china"},
  {country: "Egypt", short: "eg", url: "egypt"},
  {country: "France", short: "fr", url: "france"},
  {country: "Germany", short: "de", url: "germany"},
  {country: "Greece", short: "gr", url: "greece"},
  {country: "Hong Kong", short: "hk", url: "hong-kong"},
  {country: "India", short: "in", url: "india"},
  {country: "Ireland", short: "ie", url: "ireland"},
  {country: "Israel", short: "il", url: "israel"},
  {country: "Italy", short: "it", url: "italy"},
  {country: "Japan", short: "jp", url: "japan"},
  {country: "Netherlands", short: "nl", url: "netherlands"},
  {country: "Norway", short: "no", url: "norway"},
  {country: "Pakistan", short: "pk", url: "pakistan"},
  {country: "Peru", short: "pe", url: "peru"},
  {country: "Philippines", short: "ph", url: "philippines"},
  {country: "Portugal", short: "pt", url: "portugal"},
  {country: "Romania", short: "ro", url: "romania"},
  {country: "Russian Federation", short: "ru", url: "russia"},
  {country: "Singapore", short: "sg", url: "singapore"},
  {country: "Spain", short: "es", url: "spain"},
  {country: "Sweden", short: "se", url: "sweden"},
  {country: "Switzerland", short: "ch", url: "switzerland"},
  {country: "Taiwan", short: "tw", url: "taiwan"},
  {country: "Ukraine", short: "ua", url: "ukraine"},
  {country: "United Kingdom", short: "gb", url: "united-kingdom"},
  {country: "United States", short: "us", url: "united-states"},
];
