export const countries = [
	{country: "Argentina", short: "ar", url: "argentina", countryPl: "Argentyna"},
	{country: "Australia", short: "au", url: "australia", countryPl: "Australia"},
	{country: "Austria", short: "at", url: "austria", countryPl: "Austria"},
	{country: "Belgium", short: "be", url: "belgium", countryPl: "Belgia"},
	{country: "Brazil", short: "br", url: "brazil", countryPl: "Brazylia"},
	{country: "Bulgaria", short: "bg", url: "bulgaria", countryPl: "Bułgaria"},
	{country: "Canada", short: "ca", url: "canada", countryPl: "Kanada"},
	{country: "China", short: "cn", url: "china", countryPl: "Chiny"},
	{country: "Colombia", short: "co", url: "colombia", countryPl: "Kolumbia"},
	{country: "Cuba", short: "cu", url: "cuba", countryPl: "Kuba"},
	{country: "Czech Republic", short: "cz", url: "czech-republic", countryPl: "Czechy"},
	{country: "Egypt", short: "eg", url: "egypt", countryPl: "Egipt"},
	{country: "France", short: "fr", url: "france", countryPl: "Francja"},
	{country: "Germany", short: "de", url: "germany", countryPl: "Niemcy"},
	{country: "Greece", short: "gr", url: "greece", countryPl: "Grecja"},
	{country: "Hong Kong", short: "hk", url: "hong-kong", countryPl: "Hongkong"},
	{country: "Hungary", short: "hu", url: "hungary", countryPl: "Węgry"},
	{country: "India", short: "in", url: "india", countryPl: "Indie"},
	{country: "Indonesia", short: "id", url: "indonesia", countryPl: "Indonezja"},
	{country: "Ireland", short: "ie", url: "ireland", countryPl: "Irlandia"},
	{country: "Israel", short: "il", url: "israel", countryPl: "Izrael"},
	{country: "Italy", short: "it", url: "italy", countryPl: "Włochy"},
	{country: "Japan", short: "jp", url: "japan", countryPl: "Japonia"},
	{country: "Latvia", short: "lv", url: "latvia", countryPl: "Łotwa"},
	{country: "Lithuania", short: "lt", url: "lithuania", countryPl: "Litwa"},
	{country: "Malaysia", short: "my", url: "malaysia", countryPl: "Malezja"},
	{country: "Mexico", short: "mx", url: "mexico", countryPl: "Meksyk"},
	{country: "Morocco", short: "ma", url: "morocco", countryPl: "Maroko"},
	{country: "Netherlands", short: "nl", url: "netherlands", countryPl: "Holandia"},
	{country: "New Zealand", short: "nz", url: "new-zealand", countryPl: "Nowa Zelandia"},
	{country: "Nigeria", short: "ng", url: "nigeria", countryPl: "Nigeria"},
	{country: "Norway", short: "no", url: "norway", countryPl: "Norwegia"},
	{country: "Philippines", short: "ph", url: "philippines", countryPl: "Filipiny"},
	{country: "Poland", short: "pl", url: "poland", countryPl: "Polska"},
	{country: "Portugal", short: "pt", url: "portugal", countryPl: "Portugalia"},
	{country: "Romania", short: "ro", url: "romania", countryPl: "Rumunia"},
	{country: "Russia", short: "ru", url: "russia", countryPl: "Rosja"},
	{country: "Saudi Arabia", short: "sa", url: "saudi-arabia", countryPl: "Arabia Saudyjska"},
	{country: "Serbia", short: "rs", url: "serbia", countryPl: "Serbia"},
	{country: "Singapore", short: "sg", url: "singapore", countryPl: "Singapur"},
	{country: "South Africa", short: "za", url: "south-africa", countryPl: "Republika Południowej Afryki"},
	{country: "Slovakia", short: "sk", url: "slovakia", countryPl: "Słowacja"},
	{country: "Slovenia", short: "si", url: "slovenia", countryPl: "Słowenia"},
	{country: "Thailand", short: "th", url: "thailand", countryPl: "Tajlandia"},
	{country: "Turkey", short: "tr", url: "turkey", countryPl: "Turcja"},
	{country: "Taiwan", short: "tw", url: "taiwan", countryPl: "Tajwan"},
	{country: "Ukraine", short: "ua", url: "ukraine", countryPl: "Ukraina"},
	{country: "United States", short: "us", url: "united-states", countryPl: "Stany Zjednoczone"},
	{country: "Venezuela", short: "ve", url: "venezuela", countryPl: "Wenezuela"},
];